# Default values for vault-secret.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

prometheus-postgres-exporter:
  config:
    datasource:
      host: grafana-psql-pgcluster-r.grafana.svc
      passwordSecret:
        name: grafana-psql-pgcluster-superuser
        key: password

  serviceMonitor:
    enabled: true

pooler:
  enabled: false


image:
  repository: ghcr.io/cloudnative-pg/postgresql
  tag: 15.3-6
size: 3
storage:
  storageClass: basic
  size: 1Gi
walStorage:
  storageClass: basic
  size: 1Gi
resources:
  requests:
    memory: "32Mi"
    cpu: "50m"
  # limits:
  #   memory: "128Mi"
  #   cpu: "100m"




postgresql: {}

clusterReplication: false

backup: 
  # Options:
  #  - none
  #  - physical
  #  - logical
  type: "none"
  schedule: "0 */10 * * * *" # Required seconds!!!
  bucket:
    endpointURL: ""
    dbClusterName: ""
    region: "us-east-1"
    class: "default"
    vault:
      authPath: "jwt-hub"
      awsBackend: "aws"
      address: "https://vault.vault.svc.cluster.local:8200"

bootstrap:
  # Options: 
  #   - none
  #   - empty-db
  #   - offline-logical
  #   - physical
  #   - streaming-replication
  #   - online-logical
  type: "none"

  # Reovery target for PITR. Only works for type: physical
  # recoveryTarget:
  #   targetTime: "2023-06-28 22:03:00.00000+00"
  dbClusterName: bootstrap-origin
  bucket:
    vault:
      awsRole: "backup-reader"
      authPath: "jwt-hub"
      awsBackend: "aws-readygop"
      address: "https://vault.vault.svc.cluster.local:8200"
    endpointURL: ""
    path: "s3://bucket-name"
  connection:
    host: postgres
    user: streaming_replica
    dbname: postgres
    password:
      name: db-credentials
      key: password


kubeClusterName: hub








