{{- if eq .Values.bootstrap.initdb.secret.type  "vault" }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "{{ include "cnpg-cluster.fullname" . }}-init-user"
spec:
  path: {{ .Values.bootstrap.initdb.secret.vault.path }}
  method: "GET"
  provider:
    server: "{{ .Values.bootstrap.initdb.secret.vault.address }}"
    auth:
      jwt:
        path: "{{ .Values.bootstrap.initdb.secret.vault.authPath }}"
        role: "{{ .Values.bootstrap.initdb.secret.vault.autRole }}"

        # ... or retrieve a Kubernetes service account token via the `TokenRequest` API
        kubernetesServiceAccountToken:
          serviceAccountRef:
            name: "{{ include "cnpg-cluster.fullname" . }}-init-user"
          # `audiences` defaults to `["vault"]` it not supplied
          audiences:
          - "{{ .Values.bootstrap.initdb.secret.vault.address }}"
          # `expirationSeconds` defaults to 10 minutes if not supplied
          expirationSeconds: 600
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ include "cnpg-cluster.fullname" . }}-init-user"
spec:
  refreshInterval: "1h"
  target:
    name: "{{ include "cnpg-cluster.fullname" . }}-init-user"
    template:
      engineVersion: v2
      data:
        username:  "{{ `{{ .username }}` }}"
        password: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: "{{ include "cnpg-cluster.fullname" . }}-init-user"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cnpg-cluster.fullname" . }}-init-user

{{- end }}
